# array 관련 함수 사용
 
## 각 성분에 적용되는 함수
 
numpy에서는 array에 적용할 수 있는 다양한 함수를 제공한다. 이들 중 array의 각 성분에 대하여 특정한 계산을 일괄적으로 수행하기 위한 함수들이 있다.
 
 
** numpy에서 한 개의 array의 각 성분에 적용되는 함수 정리**

- abs        : 각 성분의 절댓값 계산

- sqrt       : 각 성분의 제곱근 계산 (array ** 0.5 의 결과와 동일) 

- square     :각 성분의 제곱 계산 (array ** 2 의 결과와 동일) 

- exp        :각 성분을 무리수 e의 지수로 삼은 값을 계산 

- log, log10, log2    : 자연로그(밑이 e), 상용로그(밑이 10), 밑이 2인 로그를 계산 

- sign       :각 성분의 부호 계산 (+인 경우 1, -인 경우 -1, 0인 경우 0) 

- ceil       :각 성분의 소수 첫 번째 자리에서 올림한 값을 계산 

- floor      :각 성분의 소수 첫 번째 자리에서 내림한 값을 계산 

- isnan      :각 성분이 NaN(Not a Number)인 경우 True를, 그렇지 않은 경우 False를 반환 

- isinf      :각 성분이 무한대(infinity)인 경우 True를, 그렇지 않은 경우 False를 반환 

- cos, cosh, sin, sinh, tan, tanh    : 각 성분에 대한 삼각함수 값을 계산 


In [35]:
import numpy as np

In [36]:
arr = np.arange(1,10)

In [37]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.square(arr)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [39]:
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

만약 크기가 같은 두 개의 array x, y가 아래와 같이 주어졌을 때, np.maximum() 함수를 적용하면 두 array를 동일한 위치의 성분끼리 비교하여 값이 더 큰 성분을 선택, 새로운 array로 리턴한다.

In [40]:
x = np.random.randn(8)
y = np.random.randn(8)

In [41]:
x

array([ 1.00361594, -0.93926972,  1.02171487,  0.70135733,  1.40277287,
        0.66000435, -0.55700724, -0.00630813])

In [42]:
y

array([ 1.47609645, -1.20379729, -1.07534692, -1.61808922, -0.2225007 ,
       -1.15396431,  0.24198625, -0.45052085])

In [43]:
#x 와 y의 위치값을 비교하여 maximum을 수행
np.maximum(x,y)

array([ 1.47609645, -0.93926972,  1.02171487,  0.70135733,  1.40277287,
        0.66000435,  0.24198625, -0.00630813])

** numpy에서 두 개의 array의 각 성분에 적용되는 함수 정리 **


- add         :                         두 array에서 동일한 위치의 성분끼리 더한 값을 계산 (arr1 + arr2의 결과와 동일) 

- subtract    :               두 array에서 동일한 위치의 성분끼리 뺀 값을 계산 (arr1 - arr2의 결과와 동일) 

- multiply    :              두 array에서 동일한 위치의 성분끼리 곱한 값을 계산 (arr1 * arr2의 결과와 동일) 

- divide      :             두 array에서 동일한 위치의 성분끼리 나눈 값을 계산 (arr1 / arr2의 결과와 동일) 

- maximum     :            두 array에서 동일한 위치의 성분끼리 비교하여 둘 중 최댓값을 반환 

- minimum     :           두 array에서 동일한 위치의 성분끼리 비교하여 둘 중 최솟값을 반환 


## 통계 함수
 
 
numpy의 array에 적용되는 통계 함수 정리

** numpy에서 array에 적용되는 통계함수 정리 **

- sum  :                     전체 성분의 합을 계산 

- mean  :                    전체 성분의 평균을 계산 

- std, var :                  전체 성분의 표준편차, 분산을 계산 

- min, max  :                전체 성분의 최솟값, 최댓값을 계산 

- argmin, argmax :            전체 성분의 최솟값, 최댓값이 위치한 인덱스를 반환 

- cumsum  :                   맨 첫번째 성분부터 각 성분까지의 누적합을 계산 (0에서부터 계속 더해짐) 

- cumprod  :                 맨 첫번째 성분부터 각 성분까지의 누적곱을 계산 (1에서부터 계속 곱해짐) 

In [44]:
arr = np.random.randn(5,4)

In [45]:
arr

array([[-0.02918725, -0.60926701,  0.42322609,  1.4200465 ],
       [ 0.99209058,  1.9448833 ,  0.07778033,  0.19592971],
       [-0.09879754,  3.41631214, -0.08050296,  0.57988365],
       [ 0.6487635 , -0.72647959, -0.36809462,  1.46037492],
       [ 0.02267972, -1.96656152,  0.1041369 , -1.05143002]])

In [46]:
# 'arr' array의 모든 값에 대하여 sum을 수행
arr.sum()

6.3557868414336465

In [47]:
arr.mean()

0.3177893420716823

In [48]:
# 행방향으로 열 값들을 전체 sum을 수행 (각 열의 합을 구함)
arr.sum(axis=0)

array([ 1.53554902,  2.05888733,  0.15654574,  2.60480476])

In [49]:
# 열방향으로 행의 값들을 전체 sum을 수행 ( 각 행의 합을 구함)
arr.sum(axis=1)

array([ 1.20481834,  3.21068393,  3.81689529,  1.0145642 , -2.89117492])

In [50]:
# 조건부 연산
arr > 0

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True, False, False,  True],
       [ True, False,  True, False]], dtype=bool)

In [51]:
# True값 
(arr > 0).sum()

12

## 정렬 함수 및 기타 함수

In [52]:
arr = np.random.randn(8)

In [53]:
arr

array([-0.89586198, -2.1738823 ,  0.85250672, -0.94882067, -0.79086555,
        0.1988241 , -0.18247359, -1.01136384])

위와 같은 arr array가 정의되어 있다고 할 때, np.sort() 함수를 적용하면 arr array의 성분이 오름차순으로(크기가 커지는 순서대로) 정렬됩니다.

In [54]:
# 오름차순 정렬
np.sort(arr)

array([-2.1738823 , -1.01136384, -0.94882067, -0.89586198, -0.79086555,
       -0.18247359,  0.1988241 ,  0.85250672])

In [55]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([ 0.85250672,  0.1988241 , -0.18247359, -0.79086555, -0.89586198,
       -0.94882067, -1.01136384, -2.1738823 ])

만약 위의 경우에서 내림차순으로 정렬하고 싶다면, np.sort(arr)[::-1]을 실행하면 된다. 
 
정렬 함수는 2차원 array에도 적용할 수 있습니다. 

In [56]:
# 2차원 array 정렬
arr = np.random.randn(5,3)

In [57]:
arr

array([[ 0.1450054 ,  0.46572219, -0.7858127 ],
       [-0.29019684, -0.52600326, -0.06249059],
       [-0.20862485, -0.08037487, -0.81524624],
       [-0.16471237, -0.5369893 ,  0.03536702],
       [ 1.94777723,  1.1629859 ,  0.62633104]])

2차원 arr array를 하나 정의하였을 때, np.sort(arr, axis=0)을 실행하면 '행 방향'으로 오름차순 정렬이 이루어진다. axis 인자의 값을 1로 바꾸면 '열 방향'으로 오름차순 정렬이 이루어질 것이다.

In [58]:
# 행방향으로 열의 값을 오름차순 정렬
np.sort(arr, axis=0)

array([[-0.29019684, -0.5369893 , -0.81524624],
       [-0.20862485, -0.52600326, -0.7858127 ],
       [-0.16471237, -0.08037487, -0.06249059],
       [ 0.1450054 ,  0.46572219,  0.03536702],
       [ 1.94777723,  1.1629859 ,  0.62633104]])

In [59]:
# 열방향으로 행의 값을 오름차순 정렬
np.sort(arr, axis = 1)

array([[-0.7858127 ,  0.1450054 ,  0.46572219],
       [-0.52600326, -0.29019684, -0.06249059],
       [-0.81524624, -0.20862485, -0.08037487],
       [-0.5369893 , -0.16471237,  0.03536702],
       [ 0.62633104,  1.1629859 ,  1.94777723]])

만약 길이가 아주 긴 large_arr array가 정의되어 있을 때, 해당 array 상에서 상위 5%에 위치하는 값은 다음과 같이 찾아낼 수 있다.

In [2]:
import numpy as np

large_arr = np.random.randn(150)

In [3]:
large_arr

array([ 0.70123876, -1.29076038, -0.53599921, -0.69719886, -0.61737156,
        0.27386564,  0.85809818, -1.16863045,  0.24702853, -0.01613725,
       -0.39239859,  0.3935763 ,  0.4096639 , -0.46106825, -1.61883905,
       -0.27152481,  0.14707679,  1.47833931,  0.23952351, -0.59755908,
        0.73575994,  1.17003855, -0.37286655, -0.76913426,  0.79972582,
       -0.58934099, -0.09634344,  1.05600203, -0.63378617,  1.44362999,
        1.75961276,  1.26572085,  0.02444625, -0.93074521, -0.83521289,
       -0.38731283,  0.88820413,  0.35588116, -0.20437739,  1.47946685,
       -1.64338966, -1.28211607, -1.93954313, -0.06609639,  2.62015958,
        0.71326147,  0.48801752,  0.81532151, -1.20548031, -0.32090358,
        1.17820178, -1.80194594,  0.0197851 , -1.1917756 , -0.10489591,
        0.31809376, -0.50268475, -0.12959796, -0.43790424,  0.11811734,
       -0.41730474, -1.61359822, -0.19356063, -0.25695699,  0.52288461,
       -1.32442361, -0.54560414,  0.86440895,  0.55420177,  0.96

In [62]:
#상위 5%의 값을 찾기

In [4]:
np.sort(large_arr)[::-1]  # 먼저 내림차순으로 sort

array([ 2.62015958,  2.42820981,  2.27716865,  1.88466068,  1.88267221,
        1.86532626,  1.75961276,  1.61557969,  1.54215156,  1.50130904,
        1.47946685,  1.47833931,  1.44362999,  1.40104853,  1.30112061,
        1.26572085,  1.24601418,  1.24284784,  1.22803427,  1.17820178,
        1.17003855,  1.07142881,  1.05600203,  1.05296343,  1.00569085,
        0.98293861,  0.96836068,  0.93795607,  0.88820413,  0.86440895,
        0.85809818,  0.81532151,  0.81368266,  0.79972582,  0.78348254,
        0.73575994,  0.71326147,  0.7110547 ,  0.70123876,  0.68850369,
        0.68346022,  0.68183439,  0.63744905,  0.63278597,  0.63204866,
        0.61710916,  0.59703517,  0.58874626,  0.55420177,  0.55155278,
        0.54923279,  0.52288461,  0.48801752,  0.42141633,  0.41741125,
        0.41689921,  0.41202809,  0.4096639 ,  0.3935763 ,  0.35588116,
        0.31809376,  0.28791656,  0.27386564,  0.25267354,  0.24702853,
        0.23952351,  0.23542331,  0.15586466,  0.14707679,  0.13

In [5]:
np.sort(large_arr)[::-1][int(0.05 * len(large_arr))]       
# 내림차순된 array에서 0.05 * 150을 수행하여 int값으로 변경, 계산된 7번째 자리값이 5%의 값이다.     

1.6155796901952166

In [7]:
0.05*150

7.5

large_arr을 먼저 내림차순으로 정렬한 뒤, int(0.05 * len(large_arr))을 통해 상위 5%에 해당하는 인덱스를 계산한 후, 이를 사용하여 정렬 결과에 대한 인덱싱을 수행하는 과정으로 진행.
 
마지막으로, 중복된 성분을 포함하고 있는 array에 대하여, np.unique() 함수를 사용하면 중복된 값을 제외한 유니크한 값만을 추출할 수 있다. 예를 들어 해당 array의 이름이 names 였다면, np.unique(names)을 실행하면 중복된 성분이 제거된 새로운 array를 얻을 수 있다.
 

In [65]:
# 중복된 값 제거하기 - unique()
names = np.array(['charles', 'hyunsuk','charles', 'hayoung','hyunsuk','joohee','joohee'])
ints = np.array([3,3,3,4,4,1,1,2,5,5,6,8])

In [66]:
np.unique(names)

array(['charles', 'hayoung', 'hyunsuk', 'joohee'],
      dtype='<U7')

In [67]:
np.unique(ints)

array([1, 2, 3, 4, 5, 6, 8])