In [1]:
import numpy as np

In [2]:
data = np.genfromtxt('./data/ratings.dat', delimiter = '::', dtype=np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

## 데이터 컬럼 내용
# user_id :: item :: rating :: timestamp

In [3]:
# 5행까지 확인
data[:6,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268]], dtype=int64)

In [5]:
data.shape

(1000209, 4)

# 문제) 전체 평균 평점 계산하기

In [6]:
mean_rating_total = data[:, 2].mean()
mean_rating_total

3.581564453029317

# 문제) 각 사용자 별 평균 평점 계산하기

In [7]:
# user에 대해 unique 값만 먼저 뽑기
user_id = np.unique(data[:,0])

In [8]:
user_id[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [9]:
user_id.shape

(6040,)

In [10]:
# 빈 리스트 생성
mean_rating_by_user_list = []

for user in user_id:
    data_for_user = data[data[:,0] == user, :]           # 특정 user_id 값들의 array를 저장한 변수 (unique 값별로 저장)
    mean_rating_for_user = data_for_user[:, 2].mean()    # 특정 user_id의 평점을 평균
    mean_rating_by_user_list.append([user, mean_rating_for_user]) # 빈 리스트에 결과 넣기

In [11]:
data_for_user[:10]

array([[     6040,       573,         4, 956704056],
       [     6040,       589,         4, 956704996],
       [     6040,         1,         3, 957717358],
       [     6040,      2068,         4, 997453982],
       [     6040,       592,         2, 956716016],
       [     6040,       593,         5, 956703954],
       [     6040,      3016,         2, 956716157],
       [     6040,      3017,         1, 956716519],
       [     6040,      2070,         4, 956715676],
       [     6040,      1419,         3, 956704056]], dtype=int64)

In [14]:
mean_rating_by_user_list[:10]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

# 결과를 파일에 writing하여 저장하기

In [19]:
# 리스트 -> array 타입으로 변환
mean_rating_by_user_list_array = np.array(mean_rating_by_user_list, dtype=np.float64)
mean_rating_by_user_list_array.shape

(6040, 2)

In [21]:
#파일에 저장
np.savetxt("./data/mean_rating_by_user.csv", mean_rating_by_user_list_array, fmt="%.3f", delimiter=',')